version: '3.8'

services:

  api:
    build: ./api
    ports:
      - 5000:5000
    depends_on:
      - mongo

  www:
    build: ./www
    stdin_open: true
    ports:
      - 8080:8080

  caddy:
    image: caddy/caddy:2.6-alpine
    container_name: caddy-service
    ports: 
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
  caddy_data:
  caddy_config:



