version: '3.8'

services:

  api:
    build: ./api
    expose:
      - 5000
    ports:
      - 5000:5000
    command: npm run start

  www:
    build: ./www
    expose:
      - 8080
    ports:
      - 8080:8080
    command: npm run start

  caddy: 
    image: caddy/caddy:2.6-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:            
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - www

volumes:
  caddy_data:
  caddy_config: 
